-
  name: Set bash prompt
  hosts: playground
  vars:
    prompt: export PS1="\A \[\e[01;33m\]\h\[\e[01;m\]:\[\e[01;36m\]\W\[\e[01;m\]\\$ "
  tasks:
    -
      name: Edit .bashrc
      lineinfile:
        path: ~/.bashrc
        line: '{{ prompt }}'
