-
  name: Update and upgrade
  hosts: playground
  become: yes
  tasks:
    - name: Update all packages to their latest version (Debian)
      apt:
        name: "*"
        state: latest
      when: ansible_os_family=='Debian'
    - name: Update all packages to their latest version
      yum:
        name: "*"
        state: latest
      when: ansible_os_family=='RedHat' or ansible_os_family=='SUSE'
